### ISSUE TITLE
Question mark(?) is not be able to add as card.

### ISSUE THREAD

**Issue by ryonryon** [agnosticful/saraka-mobile#43]
![image](https://user-images.githubusercontent.com/35892492/54570086-75b38000-499a-11e9-8a69-5192d4bccbfb.png)

![image](https://user-images.githubusercontent.com/35892492/54570092-79df9d80-499a-11e9-80ab-5326fa46761a.png)

**Comment by axross** [comment]
@ryotogashi Do you want to take this issue?

**Comment by axross** [comment]
## Check list

- Validation at the mobile app
- Validation at the backend
