### ISSUE TITLE
Displays statistics for each card.

### ISSUE THREAD

**Issue by ryonryon** [agnosticful/saraka-mobile#53]
from #33

**Comment by axross** [comment]
@ryotogashi Can I take this issue? This and #51 is somewhat linked to each other. Or do you want to take #51 as well?

**Comment by axross** [comment]
I took

**Comment by axross** [comment]
- Next scheduled study date
    - "2 days later", "2 month later", "in 2019", etc
- Maturity
    - "78%"
        - 100% is: "don't forget more than 1 year"
            - `interval / (1000 * 60 * 60 * 24 * 365)` (`31536000000`)
        - Could be more than 100%
    - With a "gauge" chart
- Estimated date to be 100% maturity
    - to be not implemented now
    - kinda hard to think

**Comment by ryonryon** [comment]
I think that it's difficult to make "Forecast number of cards you will study". Because we have property "nextStudyScheduledAt" in snapshot but we don't have next's next.
How would you think to get the correct number?

**Comment by axross** [comment]
@ryotogashi 
We can calculate how much interval and when next of next one is.

Anyway, is this topic related to the issue? I got confused. If it isn't, please leave it in somewhere proper.

**Comment by ryonryon** [comment]
@axross Sorry I saw the wrong topic.

**Comment by axross** [comment]
![IMG_20190325_190816](https://user-images.githubusercontent.com/4289883/54966483-a747c080-4f31-11e9-979b-00c765735e8f.jpg)

**Comment by axross** [comment]
Hmm...

![Screenshot_20190325-201135](https://user-images.githubusercontent.com/4289883/54969168-6bfdbf80-4f3a-11e9-9318-0e85428be3a9.png)

**Comment by axross** [comment]
I'm thinking of changing to this

![IMG_20190325_201129](https://user-images.githubusercontent.com/4289883/54969167-6a33fc00-4f3a-11e9-8e43-b0cce5785500.jpg)

**Comment by axross** [comment]
Hmmmm

![]()

**Comment by axross** [comment]
Hmmm how to customize this chart...

![Screenshot_20190325-222107](https://user-images.githubusercontent.com/4289883/54973356-c4d65380-4f4c-11e9-8b9c-a4b576530cab.png)

**Comment by axross** [comment]
https://google.github.io/charts/flutter/example/axes/hidden_ticks_and_labels_axis

**Comment by axross** [comment]
Yeah

**Comment by axross** [comment]
Yes!

![Screenshot_20190325-230007](https://user-images.githubusercontent.com/4289883/54974932-e2a6b700-4f52-11e9-88a0-e1f6cd1986a8.png)

**Comment by axross** [comment]
Oh god...

![Screenshot_20190325-230840](https://user-images.githubusercontent.com/4289883/54974990-01a54900-4f53-11e9-9eb2-6d2619be61ed.png)

**Comment by axross** [comment]
Perfectってやつだ

![11638](https://user-images.githubusercontent.com/4289883/54976496-c5c0b280-4f57-11e9-865c-20835138364c.jpg)

**Comment by axross** [comment]
I think this is pretty much better 🤔 

![11647](https://user-images.githubusercontent.com/4289883/54977848-c78c7500-4f5b-11e9-82ac-66136657532d.jpg)

**Comment by axross** [comment]
![11770](https://user-images.githubusercontent.com/4289883/55041230-6c08c880-4fe9-11e9-804f-4e12ee7ea0c9.jpg)
