### ISSUE TITLE
I'm stacked. want help (bottom overflowed by infinity pixels)

### ISSUE THREAD

**Issue by ryonryon** [agnosticful/saraka-mobile#58]
![image](https://user-images.githubusercontent.com/35892492/54798055-021ca780-4c14-11e9-9f8d-dc76d821c5e7.png)

I/flutter ( 8186): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8186): The following assertion was thrown during performLayout():
I/flutter ( 8186): RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter ( 8186): This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter ( 8186): inside another render object that allows its children to pick their own size.
I/flutter ( 8186): The nearest ancestor providing an unbounded height constraint is:
I/flutter ( 8186):   RenderFlex#ff0dc NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8186):   creator: Column ← DecoratedBox ← ConstrainedBox ← Container ← Container ← SimpleBarChart ←
I/flutter ( 8186):   RepaintBoundary-[<6>] ← IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive
I/flutter ( 8186):   ← AutomaticKeepAlive ← SliverList ← ⋯
I/flutter ( 8186):   parentData: <none> (can use size)
I/flutter ( 8186):   constraints: BoxConstraints(w=360.7, h=180.0)
I/flutter ( 8186):   size: MISSING
I/flutter ( 8186):   direction: vertical
I/flutter ( 8186):   mainAxisAlignment: center
I/flutter ( 8186):   mainAxisSize: max
I/flutter ( 8186):   crossAxisAlignment: center
I/flutter ( 8186):   verticalDirection: down
I/flutter ( 8186): The constraints that applied to the RenderCustomMultiChildLayoutBox were:
I/flutter ( 8186):   BoxConstraints(0.0<=w<=360.7, 0.0<=h<=Infinity)
I/flutter ( 8186): The exact size it was given was:
I/flutter ( 8186):   Size(360.7, Infinity)
I/flutter ( 8186): See https://flutter.io/layout/ for more information.
I/flutter ( 8186): 
I/flutter ( 8186): When the exception was thrown, this was the stack:
I/flutter ( 8186): #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1749:9)
I/flutter ( 8186): #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
I/flutter ( 8186): #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
I/flutter ( 8186): #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
I/flutter ( 8186): #4      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:5)
I/flutter ( 8186): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 8186): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 8186): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #16     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:410:13)
I/flutter ( 8186): #17     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
I/flutter ( 8186): #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
I/flutter ( 8186): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 8186): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter ( 8186): #23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter ( 8186): #24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter ( 8186): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #42     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8186): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8186): #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
I/flutter ( 8186): #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8186): #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8186): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter ( 8186): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8186): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #68     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3030:14)
I/flutter ( 8186): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 8186): #70     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8186): #71     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter ( 8186): #72     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 8186): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter ( 8186): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 8186): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 8186): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 8186): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 8186): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 8186): #82     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 8186): #83     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 8186): (elided 3 frames from package dart:async)
I/flutter ( 8186): 
I/flutter ( 8186): The following RenderObject was being processed when the exception was fired:
I/flutter ( 8186):   RenderCustomMultiChildLayoutBox#07e2d relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8186):   creator: CustomMultiChildLayout ← BarChart ← Container ← Column ← DecoratedBox ← ConstrainedBox ←
I/flutter ( 8186):   Container ← Container ← SimpleBarChart ← RepaintBoundary-[<6>] ← IndexedSemantics ←
I/flutter ( 8186):   NotificationListener<KeepAliveNotification> ← ⋯
I/flutter ( 8186):   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
I/flutter ( 8186):   constraints: BoxConstraints(0.0<=w<=360.7, 0.0<=h<=Infinity)
I/flutter ( 8186):   size: Size(360.7, Infinity)
I/flutter ( 8186): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 8186):   RenderSemanticsGestureHandler#0b32b NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8186):     RenderPointerListener#4dd2f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8186):       ChartContainerRenderObject<String>#3bec7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 8186): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8186): Another exception was thrown: A RenderFlex overflowed by Infinity pixels on the bottom.

**Comment by axross** [comment]
Use ` ``` ` next time
